version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Init
          command: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
