version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn test a
workflows:
  version: 1
  example:
    jobs:
      - test
