version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Init
          command: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
  deploy-job:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Init
          command: yarn
      - run:
          name: Login
          command: ./node_modules/.bin/firebase login
      - run:
          name: Add
          command: ./node_modules/.bin/firebase use --add
      - run:
          name: Deployss
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project fir-circle-ci-347de
workflows:
  version: 1
  deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
